### PR TITLE
Made sure image data wasn't being written to memory

### PR DESCRIPTION
**Pull request by betaredex**

### CODE REVIEW

**Comment by rudolphpienaar** [comment]
hey @betaredex @danmcp --

So you reverted to the old `pman` and `pfioh` ?

I was working on accommodating both swift and non-swift cases for pfioh/pman -- I was actually seeing if I could get the "broken" pfioh working by replacing the swift calls. Do you think this is still worthwhile exploring?

**Comment by danmcp** [comment]
@rudolphpienaar Yes, I reverted the change while Elliot works through the issues.  I didn't want to leave master in a broken state any longer.  It is still reasonable to explore your improvement as well.  Not sure how long you were expecting it to take.

**Comment by rudolphpienaar** [comment]
Yep, I agree with reverting -- also not wanted to have master in a broken state. I was testing some logic on my end on Elliot's code: essentially reverted the calls from `swift_storage` to using `mount_dir` -- there were some gotchas, but it looks like the `storePut` worked. I was checking the `storeGet`. I'll continue with local container builds of the whole system.

**Comment by danmcp** [comment]
@rudolphpienaar This is ready for a second look.  Elliot and I believe the previous issues are worked through.

**Comment by rudolphpienaar** [comment]
ok -- I'll take a look. I'll actually build local docker images of the 
whole system and do manual testing.

**Pull request merged**
