### PR TITLE
Fixed openshift status response to be CUBE compatible

### PR DESCRIPTION
**Pull request by husky-parul**

### CODE REVIEW

**Comment by husky-parul** [comment]
@danmcp

**Comment by danmcp** [comment]
LGTM, @rudolphpienaar Please review and merge when ready

**Comment by rudolphpienaar** [comment]
Hey @husky-parul  -- Do you mind also changing the following:

1. in `bin/pman`
    update the str_version to "2.0.0.10"

2. in 'README.rst'
    Similarly update to 2.0.0.10 in the page header

3. in 'setup.py'
    Similarly update the 'version' to 2.0.0.10

**Comment by husky-parul** [comment]
@rudolphpienaar Done.

**Pull request merged**
