### PR TITLE
Added MOC health check framework

### PR DESCRIPTION
**Pull request by arnavn101**
This program provides a real-world application for pfurl project. It sends a generic command from pfurl, and recieves a unique output: a “true” status as its output when server performs exceptionally and an http error code if it is unable to properly communicate with the MOC server. Thus, the program is designed to send an email to a list of recipients if pfurl displays a http status code several times in a given interval. It can also be considered as a status fetcher used to send http-based messages to remote services such as pman and pfioh, in order to test their efficiency

### CODE REVIEW

**Comment by husky-parul** [comment]
@danmcp

**Comment by danmcp** [comment]
I am not going to do a full review given this doesn't seem quite on track.  I wouldn't expect any docker images (unless you needed a custom ChRIS plugin to validate pman is working and I wouldn't expect any email logic in this script.  The idea should be to run a basic test of pman and pfioh, validate it succeeded, reuse ids, and make the code reentrant.

I would expect any logic for emailing to be part of the program calling the script and not in the scripting itself.  An existing jenkins server would do but there are a lot of alternatives.

**Comment by rudolphpienaar** [comment]
? I'm a tad confused about this PR? Is this a `pfurl` or `pman` component?

**Comment by husky-parul** [comment]
> ? I'm a tad confused about this PR? Is this a `pfurl` or `pman` component?

It is a health check test for pman and pfioh services running on OpenShift on MOC. This might not be the right place to push this code though.

**Pull request closed without merging**
